export const USER_SETUP_BEGIN = "USER_SETUP_BEGIN";
export const USER_SETUP_DONE = "USER_SETUP_DONE" 

export const GET_GAMES_BEGIN = "GET_GAMES_BEGIN";
export const GET_GAMES_DONE = "GET_GAMES_DONE";
export const GET_GAME_BEGIN = "GET_GAME_BEGIN";
export const GET_GAME_DONE = "GET_GAME_DONE";

export const GET_GENRES_DONE = "GET_GENRES_DONE";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const RESET_INPUT = "RESET_INPUT";